services:
  app:
    container_name: todo-list-ssr
    build:
      context: .
      target: runner
    image: ${HARBOR_HOST}/to-do-list/todo-list:latest
    environment:
      NODE_ENV: production
    restart: unless-stopped

  web:
    container_name: todo-list-web
    build:
      context: .
      target: web
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped