services:
  todo-list:
    container_name: todo-list
    build: .
    image: ${HARBOR_HOST}/to-do-list/todo-list:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped