upstream ssr {
    server app:3000;
}

server {
    listen 80;

    location /assets/ {
        root /usr/share/nginx/html;
    }

    location / {
        proxy_pass http://ssr;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}