name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Deploy realizado com sucesso!"