name: Main

on:
  pull_request:
    branches:
      - main

jobs:
  hello:
    name: Hello
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Pull request para main recebido!"